/**
 * Bhoomi Sakha - Notifications View
 * Institutional Notification Center for user-scoped case alerts and statutory telemetry.
 * Connects directly to backend notifications collection and role permissions.
 */

import { notificationStore } from '../utils/notifications.js';
import { caseService } from '../api/cases.js';
import { authService } from '../api/auth.js';
import { tts } from '../utils/tts.js';
import { renderInfoButton } from '../utils/infoModal.js';
import { i18n, t } from '../i18n/index.js';
import { realtimeService } from '../api/realtime.js';

export async function renderNotificationsView(container, onStateChange) {
  if (container._cleanupRealtime) {
    container._cleanupRealtime();
    container._cleanupRealtime = null;
  }

  const unsub = realtimeService.subscribeAll((eventType) => {
    if (eventType === 'notification_created' || eventType === 'reconnected') {
      renderNotificationsView(container, onStateChange);
    }
  });
  container._cleanupRealtime = unsub;

  let activeFilter = 'all'; // 'all' | 'unread'
  const user = authService.getStoredUser();

  // Loading state
  container.innerHTML = `
    <div class="px-margin-desktop py-space-xl flex flex-col items-center justify-center min-h-[50vh] text-center text-on-surface-variant gap-3">
      <span class="material-symbols-outlined text-[36px] animate-spin text-primary">progress_activity</span>
      <p class="text-sm font-medium">Fetching verified alerts & statutory notifications...</p>
    </div>
  `;

  let userNotifications = [];
  if (user && user.user_id) {
    try {
      const raw = await caseService.getUserNotifications(user.user_id);
      if (Array.isArray(raw)) {
        userNotifications = raw.map(b => ({
          id: b.notification_id,
          category: b.type ? b.type.replace(/_/g, ' ').toUpperCase() : 'CASE UPDATE',
          severity: (b.type?.includes('critical') || b.type?.includes('document')) ? 'high' : 'info',
          title: b.title,
          summary: b.message,
          timestamp: new Date(b.created_at).toLocaleString(),
          actionRoute: b.case_id 
            ? (user.role === 'officer' ? `#/officer-case-workspace?id=${b.case_id}` : `#/citizen-cases?id=${b.case_id}`)
            : (user.role === 'officer' ? '#/cases' : '#/citizen-cases'),
          actionLabel: b.case_id ? t('citizen.viewDetails', 'View Case') : t('common.details', 'Details'),
          isRead: Boolean(b.read),
          isDatabase: true,
        }));
      }
    } catch (err) {
      console.warn('Could not load user notifications from backend:', err);
    }
  }

  function render() {
    let allNotifs = [];
    if (user && user.role === 'citizen') {
      // Citizen only sees their own notifications
      allNotifs = [...userNotifications];
    } else {
      // Officer sees database notifications plus system telemetry alerts
      allNotifs = [...userNotifications, ...notificationStore.getAll()];
    }

    const unreadCount = allNotifs.filter(n => !n.isRead).length;
    const displayedNotifs = activeFilter === 'unread' 
      ? allNotifs.filter(n => !n.isRead) 
      : allNotifs;

    container.innerHTML = `
      <div class="px-margin-desktop py-space-xl flex flex-col gap-space-lg w-full max-w-5xl mx-auto animate-fade-in">
        
        <!-- Header -->
        <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-space-md border-b border-outline-variant/30 pb-space-md">
          <div class="flex flex-col gap-1">
            <div class="flex items-center gap-2">
              <span class="w-2.5 h-6 bg-secondary-container rounded-sm"></span>
              <h1 class="font-headline-lg text-headline-lg text-on-surface font-bold tracking-tight">${t('notifications.title', 'System Notifications')}</h1>
              ${unreadCount > 0 ? `
                <span class="px-2 py-0.5 rounded-full bg-error text-white font-label-sm text-xs font-bold font-tabular-data">
                  ${unreadCount} ${t('notifications.unread', 'Unread')}
                </span>
              ` : `
                <span class="px-2 py-0.5 rounded-full bg-emerald-100 text-emerald-800 font-label-sm text-xs font-semibold">
                  ${t('notifications.allCaughtUp', 'All Caught Up')}
                </span>
              `}
            </div>
            <p class="font-body-md text-body-md text-on-surface-variant">
              ${user?.role === 'citizen'
                ? t('notifications.citizenSubtitle', 'Official grievance determinations, document requests, and case progression milestones.')
                : t('notifications.subtitle', 'Application alerts, inference milestones, and statutory threshold notifications generated by Bhoomi Sakha.')}
            </p>
          </div>

          <!-- Actions -->
          <div class="flex items-center gap-2 self-start sm:self-auto">
            ${unreadCount > 0 ? `
              <button class="px-space-md py-1.5 bg-surface-container hover:bg-surface-container-high text-on-surface font-label-sm text-xs font-semibold rounded border border-outline-variant/40 flex items-center gap-1.5 transition-colors" id="markAllReadBtn" type="button">
                <span class="material-symbols-outlined text-[16px]">done_all</span>
                <span>${t('notifications.markAllRead', 'Mark All Read')}</span>
              </button>
            ` : (user?.role === 'officer' ? `
              <button class="px-space-md py-1.5 bg-surface-container-low hover:bg-surface-container text-on-surface-variant font-label-sm text-xs font-medium rounded border border-outline-variant/30 flex items-center gap-1.5 transition-colors" id="resetNotifsBtn" type="button">
                <span class="material-symbols-outlined text-[16px]">refresh</span>
                <span>${t('notifications.resetDemoAlerts', 'Reset Demo Alerts')}</span>
              </button>
            ` : '')}
          </div>
        </div>

        <!-- Filter Controls & Context Guidance -->
        <div class="flex items-center justify-between gap-2 flex-wrap">
          <div class="flex items-center gap-2">
            <button class="px-3 py-1 rounded font-label-sm text-xs font-semibold transition-all ${activeFilter === 'all' ? 'bg-primary text-on-primary shadow-sm' : 'bg-surface-container-low text-on-surface-variant hover:text-on-surface'}" id="filterAllBtn" type="button">
              ${t('notifications.filterAll', 'All')} (${allNotifs.length})
            </button>
            <button class="px-3 py-1 rounded font-label-sm text-xs font-semibold transition-all ${activeFilter === 'unread' ? 'bg-primary text-on-primary shadow-sm' : 'bg-surface-container-low text-on-surface-variant hover:text-on-surface'}" id="filterUnreadBtn" type="button">
              ${t('notifications.filterUnread', 'Unread')} (${unreadCount})
            </button>
          </div>
          <div class="flex items-center gap-space-sm font-label-sm text-xs text-on-surface-variant">
            <div class="flex items-center gap-1">
              <span>${t('notifications.severity', 'Severity')}</span>
              ${renderInfoButton('notif_severity')}
            </div>
            <div class="flex items-center gap-1">
              <span>${t('notifications.categoriesLabel', 'Categories')}</span>
              ${renderInfoButton('notif_categories')}
            </div>
            <div class="flex items-center gap-1">
              <span>${t('notifications.readState', 'Read State')}</span>
              ${renderInfoButton('notif_unread_state')}
            </div>
          </div>
        </div>

        <!-- Notification List -->
        <div class="flex flex-col gap-3" id="notificationsList">
          ${displayedNotifs.length === 0 ? `
            <div class="p-space-xl bg-surface-container-lowest rounded-xl border border-outline-variant/30 text-center flex flex-col items-center justify-center gap-2">
              <span class="material-symbols-outlined text-[36px] text-on-surface-variant/60">notifications_off</span>
              <span class="font-headline-sm text-base text-on-surface font-bold">${t('notifications.noNotifications', 'No notifications to display')}</span>
              <p class="font-body-sm text-xs text-on-surface-variant">${t('notifications.noNotificationsDesc', 'There are currently no notifications under this filter.')}</p>
            </div>
          ` : displayedNotifs.map(n => {
            const severityStyle = n.severity === 'critical'
              ? 'border-l-4 border-l-red-500 bg-red-50/20 dark:bg-red-950/20'
              : n.severity === 'high'
              ? 'border-l-4 border-l-orange-500 bg-orange-50/20 dark:bg-orange-950/20'
              : 'border-l-4 border-l-sky-500 bg-sky-50/20 dark:bg-sky-950/20';

            const unreadGlow = !n.isRead 
              ? 'border border-outline-variant/50 shadow-sm' 
              : 'opacity-85 border border-outline-variant/20 bg-surface-container-lowest';

            return `
              <div class="p-space-md rounded-xl ${severityStyle} ${unreadGlow} bg-surface-container-lowest flex flex-col md:flex-row md:items-center justify-between gap-space-sm transition-all" data-id="${n.id}">
                <div class="flex items-start gap-space-sm">
                  <div class="mt-0.5 shrink-0">
                    ${!n.isRead ? `
                      <span class="w-2.5 h-2.5 rounded-full bg-secondary-container block ring-2 ring-surface-container-lowest"></span>
                    ` : `
                      <span class="w-2.5 h-2.5 rounded-full bg-surface-container-high block"></span>
                    `}
                  </div>
                  <div class="flex flex-col gap-1">
                    <div class="flex items-center gap-2 flex-wrap">
                      <span class="px-2 py-0.5 rounded font-label-sm text-[10px] font-bold uppercase tracking-wider bg-surface-container-high text-on-surface">
                        ${n.category}
                      </span>
                      <span class="font-body-sm text-xs text-on-surface-variant font-tabular-data">${n.timestamp}</span>
                      ${!n.isRead ? `
                        <span class="px-1.5 py-0.2 rounded text-[10px] bg-secondary-fixed text-on-secondary-fixed font-bold uppercase">${t('notifications.newTag', 'New')}</span>
                      ` : ''}
                      ${n.isDatabase ? `
                        <span class="px-1.5 py-0.2 rounded text-[9px] bg-primary/10 text-primary font-semibold uppercase">Verified</span>
                      ` : ''}
                    </div>
                    <h3 class="font-headline-sm text-base text-on-surface font-semibold ${!n.isRead ? 'font-bold' : ''}">
                      ${n.title}
                    </h3>
                    <p class="font-body-sm text-xs text-on-surface-variant max-w-2xl">
                      ${n.summary}
                    </p>
                  </div>
                </div>

                <!-- Card Actions -->
                <div class="flex items-center gap-2 shrink-0 self-end md:self-center pl-6 md:pl-0">
                  <button class="notif-read-btn p-1.5 rounded text-on-surface-variant hover:text-on-surface hover:bg-surface-container transition-colors" data-id="${n.id}" aria-label="${t('common.readAloud', 'Read aloud')}" title="${t('common.readAloud', 'Read aloud')}" type="button">
                    <span class="material-symbols-outlined text-[18px]">volume_up</span>
                  </button>
                  <a class="px-3 py-1.5 rounded font-label-sm text-xs font-semibold bg-primary text-on-primary hover:bg-surface-tint transition-colors flex items-center gap-1" href="${n.actionRoute}">
                    <span>${n.actionLabel}</span>
                    <span class="material-symbols-outlined text-[14px]">arrow_forward</span>
                  </a>
                  <button class="toggle-read-btn p-1.5 rounded text-on-surface-variant hover:text-on-surface hover:bg-surface-container transition-colors" data-id="${n.id}" title="${n.isRead ? t('notifications.markAsUnread', 'Mark as Unread') : t('notifications.markAsRead', 'Mark as Read')}" type="button">
                    <span class="material-symbols-outlined text-[18px]">
                      ${n.isRead ? 'mark_email_unread' : 'check_circle'}
                    </span>
                  </button>
                </div>
              </div>
            `;
          }).join('')}
        </div>

      </div>
    `;

    // Attach event listeners
    const markAllBtn = container.querySelector('#markAllReadBtn');
    if (markAllBtn) {
      markAllBtn.addEventListener('click', async () => {
        // Mark database notifications
        const unreadDb = userNotifications.filter(n => !n.isRead);
        for (const un of unreadDb) {
          try {
            await caseService.markNotificationRead(un.id);
            un.isRead = true;
          } catch (e) {
            console.warn('Error marking read:', e);
          }
        }
        notificationStore.markAllAsRead();
        render();
        if (onStateChange) onStateChange();
      });
    }

    const resetBtn = container.querySelector('#resetNotifsBtn');
    if (resetBtn) {
      resetBtn.addEventListener('click', () => {
        notificationStore.resetAll();
        render();
        if (onStateChange) onStateChange();
      });
    }

    const filterAllBtn = container.querySelector('#filterAllBtn');
    if (filterAllBtn) {
      filterAllBtn.addEventListener('click', () => {
        activeFilter = 'all';
        render();
      });
    }

    const filterUnreadBtn = container.querySelector('#filterUnreadBtn');
    if (filterUnreadBtn) {
      filterUnreadBtn.addEventListener('click', () => {
        activeFilter = 'unread';
        render();
      });
    }

    container.querySelectorAll('.notif-read-btn').forEach(btn => {
      btn.addEventListener('click', (e) => {
        e.stopPropagation();
        const id = btn.getAttribute('data-id');
        const notif = allNotifs.find(n => n.id === id);
        if (notif) {
          const icon = btn.querySelector('.material-symbols-outlined');
          tts.speak(
            `${notif.category}. ${notif.title}. ${notif.summary}`,
            i18n.getLanguage(),
            (state) => {
              if (icon) icon.textContent = state === 'speaking' ? 'pause' : 'volume_up';
            }
          );
        }
      });
    });

    container.querySelectorAll('.toggle-read-btn').forEach(btn => {
      btn.addEventListener('click', async (e) => {
        e.stopPropagation();
        const id = btn.getAttribute('data-id');
        const notif = allNotifs.find(n => n.id === id);
        if (notif) {
          if (notif.isDatabase) {
            if (!notif.isRead) {
              try {
                await caseService.markNotificationRead(id);
                notif.isRead = true;
              } catch (err) {
                console.warn('Error updating notification read:', err);
              }
            } else {
              notif.isRead = false;
            }
          } else {
            if (notif.isRead) {
              notificationStore.markAsUnread(id);
            } else {
              notificationStore.markAsRead(id);
            }
          }
          render();
          if (onStateChange) onStateChange();
        }
      });
    });
  }

  render();
}
