/**
 * Bhoomi Sakha - Notifications View
 * Institutional Notification Center for system telemetry and statutory alerts.
 */

import { notificationStore } from '../utils/notifications.js';
import { tts } from '../utils/tts.js';
import { i18n } from '../i18n/index.js';

export function renderNotificationsView(container, onStateChange) {
  let activeFilter = 'all'; // 'all' | 'unread'

  function render() {
    const allNotifs = notificationStore.getAll();
    const unreadCount = notificationStore.getUnreadCount();
    const displayedNotifs = activeFilter === 'unread' 
      ? allNotifs.filter(n => !n.isRead) 
      : allNotifs;

    container.innerHTML = `
      <div class="px-margin-desktop py-space-xl flex flex-col gap-space-lg w-full max-w-5xl mx-auto">
        
        <!-- Header -->
        <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-space-md border-b border-outline-variant/30 pb-space-md">
          <div class="flex flex-col gap-1">
            <div class="flex items-center gap-2">
              <span class="w-2.5 h-6 bg-secondary-container rounded-sm"></span>
              <h1 class="font-headline-lg text-headline-lg text-on-surface font-bold tracking-tight">System Notifications</h1>
              ${unreadCount > 0 ? `
                <span class="px-2 py-0.5 rounded-full bg-error text-white font-label-sm text-xs font-bold font-tabular-data">
                  ${unreadCount} Unread
                </span>
              ` : `
                <span class="px-2 py-0.5 rounded-full bg-emerald-100 text-emerald-800 font-label-sm text-xs font-semibold">
                  All Caught Up
                </span>
              `}
            </div>
            <p class="font-body-md text-body-md text-on-surface-variant">
              Application alerts, inference milestones, and statutory threshold notifications generated by Bhoomi Sakha.
            </p>
          </div>

          <!-- Actions -->
          <div class="flex items-center gap-2 self-start sm:self-auto">
            ${unreadCount > 0 ? `
              <button class="px-space-md py-1.5 bg-surface-container hover:bg-surface-container-high text-on-surface font-label-sm text-xs font-semibold rounded border border-outline-variant/40 flex items-center gap-1.5 transition-colors" id="markAllReadBtn" type="button">
                <span class="material-symbols-outlined text-[16px]">done_all</span>
                <span>Mark All Read</span>
              </button>
            ` : `
              <button class="px-space-md py-1.5 bg-surface-container-low hover:bg-surface-container text-on-surface-variant font-label-sm text-xs font-medium rounded border border-outline-variant/30 flex items-center gap-1.5 transition-colors" id="resetNotifsBtn" type="button">
                <span class="material-symbols-outlined text-[16px]">refresh</span>
                <span>Reset Demo Alerts</span>
              </button>
            `}
          </div>
        </div>

        <!-- Filter Controls -->
        <div class="flex items-center gap-2">
          <button class="px-3 py-1 rounded font-label-sm text-xs font-semibold transition-all ${activeFilter === 'all' ? 'bg-primary text-on-primary shadow-sm' : 'bg-surface-container-low text-on-surface-variant hover:text-on-surface'}" id="filterAllBtn" type="button">
            All (${allNotifs.length})
          </button>
          <button class="px-3 py-1 rounded font-label-sm text-xs font-semibold transition-all ${activeFilter === 'unread' ? 'bg-primary text-on-primary shadow-sm' : 'bg-surface-container-low text-on-surface-variant hover:text-on-surface'}" id="filterUnreadBtn" type="button">
            Unread (${unreadCount})
          </button>
        </div>

        <!-- Notification List -->
        <div class="flex flex-col gap-3" id="notificationsList">
          ${displayedNotifs.length === 0 ? `
            <div class="p-space-xl bg-surface-container-lowest rounded-xl border border-outline-variant/30 text-center flex flex-col items-center justify-center gap-2">
              <span class="material-symbols-outlined text-[36px] text-on-surface-variant/60">notifications_off</span>
              <span class="font-headline-sm text-base text-on-surface font-bold">No notifications to display</span>
              <p class="font-body-sm text-xs text-on-surface-variant">There are currently no notifications under this filter.</p>
            </div>
          ` : displayedNotifs.map(n => {
            const severityStyle = n.severity === 'critical'
              ? 'border-l-4 border-l-red-500 bg-red-50/20 dark:bg-red-950/20'
              : n.severity === 'high'
              ? 'border-l-4 border-l-orange-500 bg-orange-50/20 dark:bg-orange-950/20'
              : 'border-l-4 border-l-sky-500 bg-sky-50/20 dark:bg-sky-950/20';

            const unreadGlow = !n.isRead 
              ? 'border border-outline-variant/50 shadow-sm' 
              : 'opacity-85 border border-outline-variant/20 bg-surface-container-lowest';

            return `
              <div class="p-space-md rounded-xl ${severityStyle} ${unreadGlow} bg-surface-container-lowest flex flex-col md:flex-row md:items-center justify-between gap-space-sm transition-all" data-id="${n.id}">
                <div class="flex items-start gap-space-sm">
                  <div class="mt-0.5 shrink-0">
                    ${!n.isRead ? `
                      <span class="w-2.5 h-2.5 rounded-full bg-secondary-container block ring-2 ring-surface-container-lowest"></span>
                    ` : `
                      <span class="w-2.5 h-2.5 rounded-full bg-surface-container-high block"></span>
                    `}
                  </div>
                  <div class="flex flex-col gap-1">
                    <div class="flex items-center gap-2 flex-wrap">
                      <span class="px-2 py-0.5 rounded font-label-sm text-[10px] font-bold uppercase tracking-wider bg-surface-container-high text-on-surface">
                        ${n.category}
                      </span>
                      <span class="font-body-sm text-xs text-on-surface-variant font-tabular-data">${n.timestamp}</span>
                      ${!n.isRead ? `
                        <span class="px-1.5 py-0.2 rounded text-[10px] bg-secondary-fixed text-on-secondary-fixed font-bold uppercase">New</span>
                      ` : ''}
                    </div>
                    <h3 class="font-headline-sm text-base text-on-surface font-semibold ${!n.isRead ? 'font-bold' : ''}">
                      ${n.title}
                    </h3>
                    <p class="font-body-sm text-xs text-on-surface-variant max-w-2xl">
                      ${n.summary}
                    </p>
                  </div>
                </div>

                <!-- Card Actions -->
                <div class="flex items-center gap-2 shrink-0 self-end md:self-center pl-6 md:pl-0">
                  <button class="notif-read-btn p-1.5 rounded text-on-surface-variant hover:text-on-surface hover:bg-surface-container transition-colors" data-id="${n.id}" aria-label="Read notification aloud" title="Read aloud" type="button">
                    <span class="material-symbols-outlined text-[18px]">volume_up</span>
                  </button>
                  <a class="px-3 py-1.5 rounded font-label-sm text-xs font-semibold bg-primary text-on-primary hover:bg-surface-tint transition-colors flex items-center gap-1" href="${n.actionRoute}">
                    <span>${n.actionLabel}</span>
                    <span class="material-symbols-outlined text-[14px]">arrow_forward</span>
                  </a>
                  <button class="toggle-read-btn p-1.5 rounded text-on-surface-variant hover:text-on-surface hover:bg-surface-container transition-colors" data-id="${n.id}" title="${n.isRead ? 'Mark as Unread' : 'Mark as Read'}" type="button">
                    <span class="material-symbols-outlined text-[18px]">
                      ${n.isRead ? 'mark_email_unread' : 'check_circle'}
                    </span>
                  </button>
                </div>
              </div>
            `;
          }).join('')}
        </div>

      </div>
    `;

    // Attach event listeners
    const markAllBtn = container.querySelector('#markAllReadBtn');
    if (markAllBtn) {
      markAllBtn.addEventListener('click', () => {
        notificationStore.markAllAsRead();
        render();
        if (onStateChange) onStateChange();
      });
    }

    const resetBtn = container.querySelector('#resetNotifsBtn');
    if (resetBtn) {
      resetBtn.addEventListener('click', () => {
        notificationStore.resetAll();
        render();
        if (onStateChange) onStateChange();
      });
    }

    const filterAllBtn = container.querySelector('#filterAllBtn');
    if (filterAllBtn) {
      filterAllBtn.addEventListener('click', () => {
        activeFilter = 'all';
        render();
      });
    }

    const filterUnreadBtn = container.querySelector('#filterUnreadBtn');
    if (filterUnreadBtn) {
      filterUnreadBtn.addEventListener('click', () => {
        activeFilter = 'unread';
        render();
      });
    }

    container.querySelectorAll('.notif-read-btn').forEach(btn => {
      btn.addEventListener('click', (e) => {
        e.stopPropagation();
        const id = btn.getAttribute('data-id');
        const notif = notificationStore.getAll().find(n => n.id === id);
        if (notif) {
          const icon = btn.querySelector('.material-symbols-outlined');
          tts.speak(
            `${notif.category} alert. ${notif.title}. ${notif.summary}`,
            i18n.getLanguage(),
            (state) => {
              if (icon) icon.textContent = state === 'speaking' ? 'pause' : 'volume_up';
            }
          );
        }
      });
    });

    container.querySelectorAll('.toggle-read-btn').forEach(btn => {
      btn.addEventListener('click', (e) => {
        e.stopPropagation();
        const id = btn.getAttribute('data-id');
        const notif = notificationStore.getAll().find(n => n.id === id);
        if (notif?.isRead) {
          notificationStore.markAsUnread(id);
        } else {
          notificationStore.markAsRead(id);
        }
        render();
        if (onStateChange) onStateChange();
      });
    });
  }

  render();
}
